'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useLanguage } from '../../../components/LanguageProvider';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const token=()=>typeof window==='undefined'?'':sessionStorage.getItem('expiry-tracker-token')??'';
type Approval={id:string;status:string;comment?:string|null;createdAt:string;request:{id:string;requestNumber:string;title:string;type:string;priority:string;status:string;requiredDate?:string|null;requester:{name:string;email:string}};approver:{id:string;name:string;email:string}};

export default function OfficeApprovalsPage(){
 const {lang}=useLanguage();const id=lang==='id';const[items,setItems]=useState<Approval[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState<string|null>(null);const[comment,setComment]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`${API}/office-automation/approvals`,{headers:{Authorization:`Bearer ${token()}`},cache:'no-store'});if(!r.ok)throw new Error(id?'Gagal memuat approval.':'Unable to load approvals.');setItems(await r.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load approvals.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const decide=async(item:Approval,status:'APPROVED'|'REJECTED')=>{setBusy(item.id);try{const r=await fetch(`${API}/office-automation/approvals/${item.id}/decision`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({status,comment:comment[item.id]||undefined})});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message||'Unable to decide approval.')}setItems(v=>v.map(x=>x.id===item.id?{...x,status,comment:comment[item.id]||x.comment}:x))}catch(e){setError(e instanceof Error?e.message:'Unable to decide approval.')}finally{setBusy(null)}};
 const date=(v?:string|null)=>v?new Intl.DateTimeFormat(id?'id-ID':'en-US',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
 return <main className="office-page"><style>{`.office-page{min-height:calc(100vh - 64px);padding:34px clamp(18px,4vw,52px);color:var(--chrome-text)}.office-wrap{max-width:1440px;margin:0 auto}.office-head{margin-bottom:24px}.office-eyebrow{margin:0 0 6px;color:var(--chrome-muted);font-size:10px;font-weight:850;letter-spacing:.16em}.office-head h1{margin:0;font-size:30px;letter-spacing:-.8px}.office-head p{margin:7px 0 0;color:var(--chrome-muted);font-size:12px}.office-card{border:1px solid var(--chrome-border);border-radius:16px;background:var(--chrome-surface);overflow:hidden}.office-table{width:100%;border-collapse:collapse}.office-table th,.office-table td{padding:14px 16px;text-align:left;border-bottom:1px solid var(--chrome-border);font-size:12px;vertical-align:top}.office-table th{color:var(--chrome-muted);font-size:10px;text-transform:uppercase;letter-spacing:.08em;background:var(--chrome-surface-2)}.office-table tr:last-child td{border-bottom:0}.office-title{font-weight:800}.office-sub{margin-top:4px;color:var(--chrome-muted);font-size:10px}.office-link{color:#9eacff;text-decoration:none}.office-pill{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(76,111,255,.12);color:#9eacff;font-size:10px;font-weight:800}.office-comment{width:100%;min-width:180px;min-height:58px;box-sizing:border-box;border:1px solid var(--chrome-border);border-radius:9px;background:var(--chrome-surface-2);color:var(--chrome-text);padding:9px;font:inherit;font-size:11px;resize:vertical}.office-actions{display:flex;gap:7px}.office-action{border:1px solid var(--chrome-border);background:var(--chrome-surface-2);color:var(--chrome-text);border-radius:8px;padding:7px 9px;font-size:10px;font-weight:800;cursor:pointer}.office-action.approve{background:#123326;border-color:#275d45;color:#a8ebc7}.office-action.reject{background:#3a171b;border-color:#6f2b32;color:#ffabb2}.office-action:disabled{opacity:.45}.office-error,.office-empty{padding:30px;text-align:center;color:var(--chrome-muted);font-size:12px}.office-error{color:#ffabb2}@media(max-width:850px){.office-table th:nth-child(3),.office-table td:nth-child(3),.office-table th:nth-child(4),.office-table td:nth-child(4){display:none}}@media(max-width:560px){.office-page{padding:24px 14px}.office-head h1{font-size:25px}.office-table th,.office-table td{padding:11px 9px}.office-table th:nth-child(2),.office-table td:nth-child(2){display:none}}
  `}</style><div className="office-wrap"><header className="office-head"><p className="office-eyebrow">OFFICE AUTOMATION</p><h1>{id?'Approval':'Approvals'}</h1><p>{id?'Review dan putuskan request yang membutuhkan persetujuan Anda.':'Review and decide requests that require your approval.'}</p></header><section className="office-card">{error?<div className="office-error">{error}<br/><button className="office-action" onClick={()=>void load()} style={{marginTop:10}}>{id?'Coba lagi':'Retry'}</button></div>:loading?<div className="office-empty">Loading…</div>:items.length===0?<div className="office-empty">{id?'Tidak ada approval pending.':'No approvals assigned to you.'}</div>:<div style={{overflowX:'auto'}}><table className="office-table"><thead><tr><th>Request</th><th>Requester</th><th>Due</th><th>Status</th><th>Decision</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><Link className="office-link" href={`/office/requests/${item.request.id}`}><div className="office-title">{item.request.title}</div><div className="office-sub">{item.request.requestNumber} · {item.request.type} · {item.request.priority}</div></Link></td><td>{item.request.requester.name}<div className="office-sub">{item.request.requester.email}</div></td><td>{date(item.request.requiredDate)}</td><td><span className="office-pill">{item.status}</span></td><td>{item.status==='PENDING'?<><textarea className="office-comment" value={comment[item.id]??''} onChange={e=>setComment(v=>({...v,[item.id]:e.target.value}))} placeholder={id?'Komentar keputusan (opsional)…':'Decision comment (optional)…'}/><div className="office-actions" style={{marginTop:7}}><button className="office-action approve" disabled={busy===item.id} onClick={()=>void decide(item,'APPROVED')}>{busy===item.id?'…':id?'Setujui':'Approve'}</button><button className="office-action reject" disabled={busy===item.id} onClick={()=>void decide(item,'REJECTED')}>{busy===item.id?'…':id?'Tolak':'Reject'}</button></div></>:<span style={{color:'var(--chrome-muted)',fontSize:11}}>{item.comment||'—'}</span>}</td></tr>)}</tbody></table></div>}</section></div></main>;
}
