'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useLanguage } from '../../components/LanguageProvider';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const token=()=>typeof window==='undefined'?'':sessionStorage.getItem('expiry-tracker-token')??'';
type RequestItem={id:string;requestNumber:string;title:string;type:string;priority:string;status:string;requiredDate?:string|null;requester?:{name:string}};
type Task={id:string;title:string;status:string;priority:string;dueDate?:string|null;request?:{id:string;requestNumber:string}};
type Summary={pendingRequests:number;pendingApprovals:number;openTasks:number;overdueTasks:number;myRequests:number;myTasks:number};

export default function OfficePage(){
 const{lang}=useLanguage();const id=lang==='id';const[summary,setSummary]=useState<Summary|null>(null);const[requests,setRequests]=useState<RequestItem[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const headers={Authorization:`Bearer ${token()}`};const [d,r,t]=await Promise.all([fetch(`${API}/office-automation/dashboard`,{headers,cache:'no-store'}),fetch(`${API}/office-automation/requests`,{headers,cache:'no-store'}),fetch(`${API}/office-automation/tasks`,{headers,cache:'no-store'})]);if([d,r,t].some(x=>!x.ok))throw new Error(id?'Gagal memuat dashboard Office Automation.':'Unable to load Office Automation dashboard.');setSummary(await d.json());setRequests((await r.json()).slice(0,6));setTasks((await t.json()).slice(0,6))}catch(e){setError(e instanceof Error?e.message:'Unable to load office data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const date=(v?:string|null)=>v?new Intl.DateTimeFormat(id?'id-ID':'en-US',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
 const stat=[['Pending requests',summary?.pendingRequests??0,'/office/requests'],['Pending approvals',summary?.pendingApprovals??0,'/office/approvals'],['Open tasks',summary?.openTasks??0,'/office/tasks'],['Overdue tasks',summary?.overdueTasks??0,'/office/tasks'],['My requests',summary?.myRequests??0,'/office/requests'],['My tasks',summary?.myTasks??0,'/office/tasks']];
 return <main className="office-page"><style>{`.office-page{min-height:calc(100vh - 64px);padding:34px clamp(18px,4vw,52px);color:var(--chrome-text)}.office-wrap{max-width:1440px;margin:0 auto}.office-head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:24px}.office-eyebrow{margin:0 0 6px;color:var(--chrome-muted);font-size:10px;font-weight:850;letter-spacing:.16em}.office-head h1{margin:0;font-size:30px;letter-spacing:-.8px}.office-head p:last-child{margin:7px 0 0;color:var(--chrome-muted);font-size:12px}.office-primary{display:inline-flex;align-items:center;padding:11px 15px;border-radius:11px;background:#4c6fff;color:#fff;text-decoration:none;font-size:12px;font-weight:800}.office-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:16px}.office-stat{padding:17px;border:1px solid var(--chrome-border);border-radius:15px;background:var(--chrome-surface);text-decoration:none;color:inherit}.office-stat span{display:block;color:var(--chrome-muted);font-size:10px}.office-stat strong{display:block;margin-top:8px;font-size:26px;letter-spacing:-.8px}.office-layout{display:grid;grid-template-columns:1.35fr 1fr;gap:16px}.office-card{border:1px solid var(--chrome-border);border-radius:16px;background:var(--chrome-surface);overflow:hidden}.office-card-head{padding:17px 19px;border-bottom:1px solid var(--chrome-border);display:flex;justify-content:space-between;align-items:center}.office-card-head strong{font-size:13px}.office-card-head a{color:#9eacff;font-size:10px;text-decoration:none}.office-body{padding:0 19px}.office-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid var(--chrome-border);font-size:11px}.office-row:last-child{border-bottom:0}.office-title{font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.office-sub{margin-top:4px;color:var(--chrome-muted);font-size:9px}.office-pill{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(76,111,255,.12);color:#9eacff;font-size:9px;font-weight:800}.office-empty{padding:34px 8px;text-align:center;color:var(--chrome-muted);font-size:11px}.office-error{padding:18px;border-radius:12px;background:#3a171b;border:1px solid #6f2b32;color:#ffabb2;font-size:11px;margin-bottom:16px}@media(max-width:1100px){.office-stats{grid-template-columns:repeat(3,1fr)}.office-layout{grid-template-columns:1fr}}@media(max-width:650px){.office-page{padding:24px 14px}.office-head{align-items:flex-start;flex-direction:column}.office-head h1{font-size:25px}.office-stats{grid-template-columns:repeat(2,1fr)}.office-row{grid-template-columns:1fr auto}.office-row>*:last-child{display:none}}
  `}</style><div className="office-wrap"><header className="office-head"><div><p className="office-eyebrow">OFFICE AUTOMATION</p><h1>{id?'Operasional Kantor':'Office Operations'}</h1><p>{id?'Satu workspace untuk request, approval, task, dan laporan.':'One workspace for requests, approvals, tasks and reporting.'}</p></div><Link href="/office/new" className="office-primary">＋ {id?'Request baru':'New request'}</Link></header>{error&&<div className="office-error">{error}<button onClick={()=>void load()} style={{marginLeft:10,padding:'7px 10px',borderRadius:8,border:'1px solid #6f2b32',background:'transparent',color:'inherit'}}>{id?'Coba lagi':'Retry'}</button></div>}<section className="office-stats">{stat.map(([label,value,href])=><Link href={href as string} className="office-stat" key={label as string}><span>{id?({ 'Pending requests':'Request pending','Pending approvals':'Approval pending','Open tasks':'Task terbuka','Overdue tasks':'Task terlambat','My requests':'Request saya','My tasks':'Task saya'} as Record<string,string>)[label as string]??label:label}</span><strong>{loading?'—':value}</strong></Link>)}</section><section className="office-layout"><div className="office-card"><div className="office-card-head"><strong>{id?'Request terbaru':'Recent requests'}</strong><Link href="/office/requests">{id?'Lihat semua':'View all'} →</Link></div><div className="office-body">{loading?<div className="office-empty">Loading…</div>:requests.length?requests.map(r=><Link href={`/office/requests/${r.id}`} key={r.id} className="office-row" style={{textDecoration:'none',color:'inherit'}}><div><div className="office-title">{r.title}</div><div className="office-sub">{r.requestNumber} · {r.requester?.name??'—'} · {date(r.requiredDate)}</div></div><span className="office-pill">{r.status}</span><span style={{color:'var(--chrome-muted)',fontSize:9}}>{r.priority}</span></Link>):<div className="office-empty">{id?'Belum ada request.':'No requests yet.'}</div>}</div></div><div className="office-card"><div className="office-card-head"><strong>{id?'Task saya':'My tasks'}</strong><Link href="/office/tasks">{id?'Lihat semua':'View all'} →</Link></div><div className="office-body">{loading?<div className="office-empty">Loading…</div>:tasks.length?tasks.map(t=><Link href={t.request?`/office/requests/${t.request.id}`:'/office/tasks'} key={t.id} className="office-row" style={{textDecoration:'none',color:'inherit'}}><div><div className="office-title">{t.title}</div><div className="office-sub">{t.request?.requestNumber??'—'} · {date(t.dueDate)}</div></div><span className="office-pill">{t.status}</span><span style={{color:'var(--chrome-muted)',fontSize:9}}>{t.priority}</span></Link>):<div className="office-empty">{id?'Tidak ada task.':'No tasks assigned.'}</div>}</div></div></section></div></main>;
}
