-- Employee organization fields are owned by the restored
-- 20260826140000_add_employee_organization_fields migration.
-- This migration is intentionally a no-op to preserve the original
-- migration history while avoiding duplicate User columns.
