'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const token=()=>typeof window==='undefined'?'':sessionStorage.getItem('expiry-tracker-token')??'';

type Attendance={id:string;attendanceDate:string;status:string;checkInAt:string|null;checkOutAt:string|null;checkInLat:number|null;checkInLng:number|null;checkOutLat:number|null;checkOutLng:number|null};

export default function AttendancePage(){
 const[a,setA]=useState<Attendance|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 async function load(){setLoading(true);try{const r=await fetch(`${API}/office/attendance/today`,{headers:{Authorization:`Bearer ${token()}`},cache:'no-store'});if(!r.ok)throw new Error('Unable to load attendance');setA(await r.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load attendance')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function action(kind:'CHECK_IN'|'CHECK_OUT'){setSaving(true);setError('');try{let latitude:number|undefined;let longitude:number|undefined;if(typeof navigator!=='undefined'&&navigator.geolocation){const p=await new Promise<GeolocationPosition|undefined>(resolve=>navigator.geolocation.getCurrentPosition(resolve,()=>resolve(undefined),{enableHighAccuracy:true,timeout:5000}));latitude=p?.coords.latitude;longitude=p?.coords.longitude;}const r=await fetch(`${API}/office/attendance/action`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({action:kind,latitude,longitude})});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message??'Unable to record attendance')}setA(await r.json())}catch(e){setError(e instanceof Error?e.message:'Unable to record attendance')}finally{setSaving(false)}}
 const time=(v:string|null)=>v?new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v)):'—';
 return <main style={{minHeight:'calc(100vh - 64px)',padding:'34px clamp(18px,4vw,52px)',color:'var(--chrome-text)'}}><div style={{maxWidth:900,margin:'0 auto'}}><Link href="/office" style={{color:'var(--chrome-muted)',fontSize:11,textDecoration:'none'}}>← Office Automation</Link><h1 style={{margin:'18px 0 5px',fontSize:30}}>Attendance</h1><p style={{margin:'0 0 22px',color:'var(--chrome-muted)',fontSize:12}}>Check-in and check-out with optional location capture.</p>{error&&<div style={{padding:12,marginBottom:14,borderRadius:10,background:'#3a171b',color:'#ffabb2'}}>{error}</div>}<section style={{border:'1px solid var(--chrome-border)',borderRadius:18,background:'var(--chrome-surface)',padding:24}}>{loading?<p>Loading…</p>:<><div style={{fontSize:12,color:'var(--chrome-muted)'}}>Today</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:14,margin:'18px 0'}}><div><small>Status</small><strong style={{display:'block',fontSize:22,marginTop:5}}>{a?.status??'NOT RECORDED'}</strong></div><div><small>Check-in</small><strong style={{display:'block',fontSize:22,marginTop:5}}>{time(a?.checkInAt??null)}</strong></div><div><small>Check-out</small><strong style={{display:'block',fontSize:22,marginTop:5}}>{time(a?.checkOutAt??null)}</strong></div></div><div style={{display:'flex',gap:10}}><button disabled={saving||!!a?.checkInAt} onClick={()=>void action('CHECK_IN')} style={{padding:'11px 16px',border:0,borderRadius:10,background:'#4c6fff',color:'#fff',fontWeight:800}}>Check in</button><button disabled={saving||!a?.checkInAt||!!a?.checkOutAt} onClick={()=>void action('CHECK_OUT')} style={{padding:'11px 16px',border:'1px solid var(--chrome-border)',borderRadius:10,background:'var(--chrome-surface-2)',color:'var(--chrome-text)',fontWeight:800}}>Check out</button></div></>}</section></div></main>;
}
