'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';
type Reminder = { id:string; daysBefore:number; enabled:boolean; lastSentAt:string|null; processingAt:string|null; document:{id:string;title:string;documentType:string;expiryDate:string|null;reminderEnabled:boolean;owner?:{name:string;email:string}|null} };
type Role = 'SUPERUSER'|'EDITOR'|'VIEWER';
function tokenData(){try{const token=sessionStorage.getItem('expiry-tracker-token');if(!token)return null;return {token,payload:JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))) as {role:Role}}}catch{return null}}
function fmt(v:string|null){return v?new Intl.DateTimeFormat('en-US',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'No expiry'}
function dueDate(expiry:string|null, days:number){if(!expiry)return null;const d=new Date(expiry);d.setDate(d.getDate()-days);return d}
export default function RemindersPage(){
 const [items,setItems]=useState<Reminder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[enabled,setEnabled]=useState<'all'|'true'|'false'>('all'),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[role,setRole]=useState<Role>('VIEWER'),[session,setSession]=useState<{token:string;payload:{role:Role}}|null>(null),[mounted,setMounted]=useState(false);

useEffect(()=>{
  setMounted(true);
  setSession(tokenData());
},[]);
 async function load(){if(!session)return;setLoading(true);setError('');try{const q=new URLSearchParams({page:String(page),limit:'20'});if(enabled!=='all')q.set('enabled',enabled==='true'?'true':'false');const r=await fetch(`${API_URL}/reminders?${q}`,{headers:{Authorization:`Bearer ${session.token}`}});if(!r.ok)throw new Error(r.status===401?'Session expired':r.status===403?'You do not have permission to view reminders':'Unable to load reminders');const d=await r.json();setItems(d.items??[]);setTotalPages(d.pagination?.totalPages??1)}catch(e){setError(e instanceof Error?e.message:'Unable to load reminders')}finally{setLoading(false)}}
 useEffect(()=>{
  if(mounted && session){
    setRole(session.payload.role);
    load();
  }
},[mounted,session,page,enabled]);
 async function toggle(item:Reminder){if(role==='VIEWER'||!session)return;try{const r=await fetch(`${API_URL}/documents/${item.document.id}/reminders/${item.id}`,{method:'PATCH',headers:{Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify({enabled:!item.enabled})});if(!r.ok)throw new Error('Unable to update reminder');setItems(v=>v.map(x=>x.id===item.id?{...x,enabled:!x.enabled}:x))}catch(e){setError(e instanceof Error?e.message:'Unable to update reminder')}}
 if(!mounted)return null;
 if(!session)return <main className="workspace reminders-page"><div className="reminders-empty">Please sign in again. <Link href="/">Return to sign in</Link></div></main>;
 return <main className="workspace reminders-page"><header className="workspace-head"><div><Link href="/" className="back">← Command center</Link><p className="eyebrow">NOTIFICATIONS</p><h1>Reminders</h1><p>Monitor configured expiry reminders and their delivery state.</p></div><Link href="/documents" className="primary-button">View documents</Link></header><div className="reminder-tabs">{(['all','true','false'] as const).map(v=><button key={v} onClick={()=>{setEnabled(v);setPage(1)}} className={enabled===v?'active':''}>{v==='all'?'All':v==='true'?'Enabled':'Disabled'}</button>)}</div>{error&&<div className="inline-error">{error}</div>}<section className="table-card reminders-card"><div className="table-meta"><strong>{items.length} reminders</strong><span>{loading?'Refreshing…':'Updated just now'}</span></div><div className="table-wrap"><table><thead><tr>{['Document','Reminder','Expiry','Scheduled for','Delivery',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{loading?Array.from({length:6}).map((_,i)=><tr key={i}><td colSpan={6}><div className="skeleton"/></td></tr>):items.length?items.map(item=>{const due=dueDate(item.document.expiryDate,item.daysBefore);return <tr key={item.id}><td><Link href={`/documents/${item.document.id}`} className="doc-title">{item.document.title}</Link><small>{item.document.documentType} · {item.document.owner?.name??item.document.owner?.email??'No owner'}</small></td><td className="reminder-value">{item.daysBefore} days before<small>{item.enabled?'Enabled':'Disabled'}</small></td><td>{fmt(item.document.expiryDate)}</td><td>{fmt(due?.toISOString()??null)}</td><td className={item.lastSentAt?'delivery-sent':item.processingAt?'delivery-processing':'delivery-muted'}>{item.lastSentAt?`Sent ${fmt(item.lastSentAt)}`:item.processingAt?'Processing':'Not sent'}</td><td>{role!=='VIEWER'&&<button onClick={()=>toggle(item)} className="reminder-action">{item.enabled?'Disable':'Enable'}</button>}</td></tr>}) : <tr><td colSpan={6}><div className="empty"><div>♧</div><strong>No reminders found</strong><p>No reminders match the selected filter.</p></div></td></tr>}</tbody></table></div><footer className="pagination"><span>Page {page} of {totalPages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>→</button></div></footer></section></main>
}

const style=`.reminders-page{min-height:100vh;background:#080d14;color:#f5f7fb;padding:42px clamp(20px,4vw,64px);font-family:Inter,system-ui,sans-serif}.reminders-page .workspace-head{max-width:1400px;margin:0 auto 28px}.reminders-page .workspace-head h1{color:#f8fafc}.reminders-page .workspace-head p:not(.eyebrow){color:#8d99ab}.reminders-page .back{color:#8fa1bd}.reminders-page .eyebrow{color:#71809a}.reminders-page .primary-button{background:#111a2b;color:#fff;text-decoration:none}.reminder-tabs{max-width:1400px;margin:0 auto 16px;display:flex;gap:8px}.reminder-tabs button{border:1px solid #293545;background:#0d141d;color:#dce3ed;padding:9px 14px;border-radius:9px;font-size:11px;font-weight:750;cursor:pointer}.reminder-tabs button.active{background:#273657;border-color:#334463;color:#fff}.reminders-page .table-card{max-width:1400px;background:#0d141d;border:1px solid #222e3d}.reminders-page .table-meta{border-bottom:1px solid #222e3d;color:#748197}.reminders-page .table-meta strong{color:#f5f7fb}.reminders-page th{background:#0d141d;color:#748197;border-bottom:1px solid #222e3d}.reminders-page th,.reminders-page td{border-bottom:1px solid #1b2531;padding:16px 18px}.reminders-page td{color:#dce3ed}.reminders-page .doc-title{color:#f5f7fb}.reminders-page td small{color:#748197}.reminder-value{font-weight:750}.delivery-sent{color:#54d89b!important}.delivery-processing{color:#f2bd62!important}.delivery-muted{color:#748197!important}.reminder-action{border:1px solid #334154;background:transparent;color:#dce3ed;border-radius:8px;padding:7px 10px;font-size:10px;font-weight:750;cursor:pointer}.reminders-page .pagination{color:#748197}.reminders-page .pagination button{border-color:#293545;background:#0d141d;color:#dce3ed}.reminders-page .empty{color:#748197}.reminders-page .empty strong{color:#dce3ed}.reminders-page .empty p{color:#748197}.reminders-empty{max-width:1400px;margin:auto}.reminders-empty a{color:#9bb3ff}.reminders-page .inline-error{max-width:1400px;background:#401c22;color:#ffadb4;border-color:#63313a}@media(max-width:900px){.reminders-page{padding:28px 16px}.reminders-page .workspace-head{align-items:flex-start;flex-direction:column}}`;if(typeof document!=='undefined'){const id='reminders-page-style';if(!document.getElementById(id)){const s=document.createElement('style');s.id=id;s.textContent=style;document.head.appendChild(s)}}
