'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useLanguage } from '../../../components/LanguageProvider';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const token=()=>typeof window==='undefined'?'':sessionStorage.getItem('expiry-tracker-token')??'';

export default function NewOfficeRequestPage(){
 const{lang}=useLanguage();const id=lang==='id';const router=useRouter();const[type,setType]=useState('GENERAL');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[requiredDate,setRequiredDate]=useState('');const[priority,setPriority]=useState('NORMAL');const[startDate,setStartDate]=useState('');const[endDate,setEndDate]=useState('');const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const r=await fetch(`${API}/office-automation/requests`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({type,title,description:description||undefined,startDate:startDate?new Date(startDate).toISOString():undefined,endDate:endDate?new Date(endDate).toISOString():undefined,requiredDate:requiredDate?new Date(requiredDate).toISOString():undefined,priority})});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message||(id?'Gagal membuat request.':'Unable to create request.'))}const request=await r.json();router.push(`/office/requests/${request.id}`)}catch(err){setError(err instanceof Error?err.message:'Unable to create request.')}finally{setSaving(false)}};
 return <main className="office-new"><style>{`.office-new{min-height:calc(100vh - 64px);padding:34px clamp(18px,4vw,52px);color:var(--chrome-text)}.office-wrap{max-width:900px;margin:0 auto}.office-back{color:var(--chrome-muted);text-decoration:none;font-size:11px}.office-head{margin:18px 0 20px}.office-eyebrow{margin:0 0 6px;color:var(--chrome-muted);font-size:10px;font-weight:850;letter-spacing:.15em}.office-head h1{margin:0;font-size:30px;letter-spacing:-.8px}.office-head p{margin:7px 0 0;color:var(--chrome-muted);font-size:12px}.office-form{padding:22px;border:1px solid var(--chrome-border);border-radius:18px;background:var(--chrome-surface);display:grid;gap:16px}.office-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.office-form label{display:grid;gap:7px;color:var(--chrome-text);font-size:10px;font-weight:800}.office-input,.office-select,.office-textarea{width:100%;box-sizing:border-box;border:1px solid var(--chrome-border);border-radius:10px;background:var(--chrome-surface-2);color:var(--chrome-text);padding:11px 12px;font:inherit;font-size:11px;outline:0}.office-textarea{min-height:130px;resize:vertical}.office-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:4px}.office-cancel{padding:10px 13px;border:1px solid var(--chrome-border);border-radius:9px;color:var(--chrome-text);text-decoration:none;font-size:10px;font-weight:800}.office-submit{padding:10px 14px;border:0;border-radius:9px;background:#4c6fff;color:#fff;font-size:10px;font-weight:850;cursor:pointer}.office-submit:disabled{opacity:.5}.office-error{padding:11px 13px;border-radius:10px;background:#3a171b;border:1px solid #6f2b32;color:#ffabb2;font-size:11px}@media(max-width:650px){.office-new{padding:24px 14px}.office-head h1{font-size:25px}.office-grid{grid-template-columns:1fr}.office-form{padding:17px}}
  `}</style><div className="office-wrap"><Link href="/office" className="office-back">← {id?'Kembali ke Office Automation':'Back to Office Automation'}</Link><header className="office-head"><p className="office-eyebrow">OFFICE AUTOMATION</p><h1>{id?'Buat request baru':'Create a new request'}</h1><p>{id?'Ajukan kebutuhan operasional dan pantau prosesnya dari satu tempat.':'Submit an operational request and track the workflow from one place.'}</p></header>{error&&<div className="office-error" style={{marginBottom:14}}>{error}</div>}<form className="office-form" onSubmit={submit}><div className="office-grid"><label>{id?'Jenis request':'Request type'}<select className="office-select" value={type} onChange={e=>setType(e.target.value)}>{['GENERAL','LEAVE','ATTENDANCE','LATE','WFH','OVERTIME','REIMBURSEMENT','BUSINESS_TRIP','MEETING'].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select className="office-select" value={priority} onChange={e=>setPriority(e.target.value)}><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select></label></div><label>{id?'Judul':'Title'}<input className="office-input" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder={id?'Contoh: Pengajuan perjalanan dinas':'Example: Business trip request'}/></label><label>{id?'Deskripsi':'Description'}<textarea className="office-textarea" maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)} placeholder={id?'Jelaskan kebutuhan, konteks, dan informasi pendukung…':'Describe the request, context and supporting information…'}/></label><div className="office-grid"><label>{id?'Mulai':'Start'}<input className="office-input" type="datetime-local" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>{id?'Selesai':'End'}<input className="office-input" type="datetime-local" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div><label>{id?'Tanggal dibutuhkan':'Required date'}<input className="office-input" type="datetime-local" value={requiredDate} onChange={e=>setRequiredDate(e.target.value)}/></label><div className="office-actions"><Link className="office-cancel" href="/office">{id?'Batal':'Cancel'}</Link><button className="office-submit" disabled={saving}>{saving?(id?'Menyimpan…':'Saving…'):(id?'Buat request':'Create request')}</button></div></form></div></main>;
}
