'use client';

import { useEffect, useState } from 'react';
import { useLanguage } from '../../../components/LanguageProvider';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const token=()=>typeof window==='undefined'?'':sessionStorage.getItem('expiry-tracker-token')??'';
type Report={requests:Record<string,number>;tasks:Record<string,number>;approvals:Record<string,number>;workload:Array<{assignee:{id:string;name:string;email:string}|null;openTasks:number}>;generatedAt:string};

const sum=(obj:Record<string,number>)=>Object.values(obj).reduce((a,b)=>a+b,0);
const Card=({label,value,detail}:{label:string;value:number;detail:string})=><div className="report-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;

export default function OfficeReportsPage(){
 const {lang}=useLanguage();const id=lang==='id';const[data,setData]=useState<Report|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`${API}/office-automation/reports`,{headers:{Authorization:`Bearer ${token()}`},cache:'no-store'});if(!r.ok)throw new Error(id?'Gagal memuat laporan.':'Unable to load report.');setData(await r.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load report.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 return <main className="office-page"><style>{`.office-page{min-height:calc(100vh - 64px);padding:34px clamp(18px,4vw,52px);color:var(--chrome-text)}.office-wrap{max-width:1440px;margin:0 auto}.office-eyebrow{margin:0 0 6px;color:var(--chrome-muted);font-size:10px;font-weight:850;letter-spacing:.16em}.office-head{margin-bottom:24px}.office-head h1{margin:0;font-size:30px;letter-spacing:-.8px}.office-head p{margin:7px 0 0;color:var(--chrome-muted);font-size:12px}.report-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.report-card{padding:18px;border:1px solid var(--chrome-border);border-radius:15px;background:var(--chrome-surface)}.report-card span{display:block;color:var(--chrome-muted);font-size:11px}.report-card strong{display:block;margin:8px 0 4px;font-size:30px;letter-spacing:-1px}.report-card small{color:var(--chrome-muted);font-size:10px}.report-layout{display:grid;grid-template-columns:1fr 1fr;gap:16px}.report-panel{border:1px solid var(--chrome-border);border-radius:16px;background:var(--chrome-surface);padding:20px}.report-panel h2{margin:0 0 16px;font-size:15px}.report-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:11px 0;border-bottom:1px solid var(--chrome-border);font-size:12px}.report-row:last-child{border-bottom:0}.report-bar{height:8px;border-radius:99px;background:var(--chrome-surface-2);overflow:hidden;margin-top:6px}.report-bar i{display:block;height:100%;background:linear-gradient(90deg,#4c6fff,#7c4dff);border-radius:inherit}.report-muted{color:var(--chrome-muted);font-size:10px}.report-error,.report-empty{padding:30px;text-align:center;color:var(--chrome-muted);font-size:12px}.report-error{color:#ffabb2}@media(max-width:1000px){.report-grid{grid-template-columns:repeat(2,1fr)}.report-layout{grid-template-columns:1fr}}@media(max-width:560px){.office-page{padding:24px 14px}.office-head h1{font-size:25px}.report-grid{grid-template-columns:1fr 1fr}.report-card strong{font-size:25px}}
  `}</style><div className="office-wrap"><header className="office-head"><p className="office-eyebrow">OFFICE AUTOMATION</p><h1>{id?'Laporan operasional':'Operational reports'}</h1><p>{id?'Ringkasan request, task, approval, dan beban kerja.':'Summary of requests, tasks, approvals and workload.'}</p></header>{error?<div className="report-error">{error}<br/><button onClick={()=>void load()} style={{marginTop:10,padding:'8px 12px',borderRadius:8,border:'1px solid var(--chrome-border)',background:'var(--chrome-surface)',color:'var(--chrome-text)'}}>Retry</button></div>:loading?<div className="report-empty">Loading…</div>:data&&<><section className="report-grid"><Card label={id?'Total request':'Total requests'} value={sum(data.requests)} detail={id?`${data.requests.PENDING??0} pending`:`${data.requests.PENDING??0} pending`}/><Card label={id?'Task aktif':'Open tasks'} value={Object.entries(data.tasks).filter(([k])=>k!=='COMPLETED').reduce((n,[,v])=>n+v,0)} detail={id?`${data.tasks.COMPLETED??0} selesai`:`${data.tasks.COMPLETED??0} completed`}/><Card label={id?'Approval pending':'Pending approvals'} value={data.approvals.PENDING??0} detail={id?`${data.approvals.APPROVED??0} disetujui`:`${data.approvals.APPROVED??0} approved`}/><Card label={id?'Task terbuka':'Open workload'} value={data.workload.reduce((n,x)=>n+x.openTasks,0)} detail={id?`${data.workload.length} assignee aktif`:`${data.workload.length} active assignees`}/></section><section className="report-layout"><div className="report-panel"><h2>{id?'Status request':'Request status'}</h2>{Object.entries(data.requests).map(([key,value])=><div className="report-row" key={key}><div><strong>{key}</strong><div className="report-bar"><i style={{width:`${Math.min(100,Math.round(value/Math.max(1,sum(data.requests))*100))}%`}}/></div></div><strong>{value}</strong></div>)}</div><div className="report-panel"><h2>{id?'Beban task per assignee':'Task workload by assignee'}</h2>{data.workload.length?data.workload.map(row=><div className="report-row" key={row.assignee?.id??'unassigned'}><div><strong>{row.assignee?.name??'Unassigned'}</strong><div className="report-muted">{row.assignee?.email??'—'}</div></div><strong>{row.openTasks}</strong></div>):<div className="report-muted">{id?'Belum ada task terbuka.':'No open tasks.'}</div>}</div></section></>}</div></main>;
}
